DECLARE @NAME VARCHAR(50)
DECLARE @SQL VARCHAR(1000)
SET @NAME =  DB_NAME() ;

--switch to master
USE [master]

-- take the database offline
exec ('ALTER DATABASE [' + @NAME + '] SET OFFLINE WITH ROLLBACK IMEMDIATE')

-- drop the database
exec ('DROP DATABASE ' + @NAME)

-- created the database
exec('CREATE DATABASE ' + @NAME )
-- CONTAINMENT = NONE
-- ON  PRIMARY
--( NAME = N''vmstest'', FILENAME = N''c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\vmstest.mdf'' , SIZE = 152576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
-- LOG ON
--( NAME = N''vmstest_log'', FILENAME = N''c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\vmstest_log.ldf' , SIZE = 12352KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

-- configure the database
exec('ALTER DATABASE[ ' + @NAME + '] SET COMPATIBILITY_LEVEL = 110')
exec ('ALTER DATABASE[ ' + @NAME + '] SET ANSI_NULL_DEFAULT OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET ANSI_NULLS OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET ANSI_PADDING OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET ANSI_WARNINGS OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET ARITHABORT OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET AUTO_CLOSE OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET AUTO_CREATE_STATISTICS ON')
exec ('ALTER DATABASE[ ' + @NAME + '] SET AUTO_SHRINK ON')
exec ('ALTER DATABASE[ ' + @NAME + '] SET AUTO_UPDATE_STATISTICS ON')
exec ('ALTER DATABASE[ ' + @NAME + '] SET CURSOR_CLOSE_ON_COMMIT OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET CURSOR_DEFAULT GLOBAL')
exec ('ALTER DATABASE[ ' + @NAME + '] SET CONCAT_NULL_YIELDS_NULL OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET CONCAT_NULL_YIELDS_NULL OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET NUMERIC_ROUNDABORT OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET QUOTED_IDENTIFIER OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET RECURSIVE_TRIGGERS OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET DISABLE_BROKER')
exec ('ALTER DATABASE[ ' + @NAME + '] SET AUTO_UPDATE_STATISTICS_ASYNC OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET CONCAT_NULL_YIELDS_NULL OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET TRUSTWORTHY OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET ALLOW_SNAPSHOT_ISOLATION OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET PARAMETERIZATION SIMPLE')
exec ('ALTER DATABASE[ ' + @NAME + '] SET READ_COMMITTED_SNAPSHOT OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET HONOR_BROKER_PRIORITY OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET RECOVERY SIMPLE')
exec ('ALTER DATABASE[ ' + @NAME + '] SET MULTI_USER')
exec ('ALTER DATABASE[ ' + @NAME + '] SET PAGE_VERIFY CHECKSUM')
exec ('ALTER DATABASE[ ' + @NAME + '] SET DB_CHAINING OFF')
exec ('ALTER DATABASE[ ' + @NAME + '] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )')
exec ('ALTER DATABASE[ ' + @NAME + '] SET TARGET_RECOVERY_TIME = 0 SECONDS')
exec ('ALTER DATABASE[ ' + @NAME + '] SET READ_WRITE')

exec ('USE ' + @NAME )
exec('CREATE USER [user_' + @NAME + '] FOR LOGIN [user_' + @NAME + '] WITH DEFAULT_SCHEMA=[dbo]')
exec('ALTER ROLE [db_owner] ADD MEMBER [user_' + @NAME + ']')

GO


